model:
  num_agents: 1000
  ema_param: 0.2  # exponential moving average parameter
  r_base: 0  # baseline interest
  intensity: 0.8  # intensity of policy
  inf_target: 0.04  # target inflation set by CB
  trust: 0.8
bank:
  mu_loan: 0.5
  mu_dep: 0.1
  ltv: 0.5
firm:
  adj_w: 0.1
  adj_p: 0.4 # скорость адаптации цены
  nu_2: 0.2
  sens: 0.001
household:
  ptc: 0.5  # склонность к потреблению из дохода
  sens: 0.05
  mu_k: 5
  sigma_k: 2
  mu_1: 0.012
  mu_2: 0.01
  sigma: 0.0115
  inv_cost: 40
  mean_w: 100
  sigma_w: 25